version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: productsdb
    volumes:
      - mongo_data:/data/db

  spring-crud-mongodb:
    build:
      context: ./Spring-CRUD-MongoDB
    container_name: spring-crud-mongodb
    ports:
      - "8080:9090"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/productsdb
    depends_on:
      - mongo

  mysql:
    image: mysql:8.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orderdb
      MYSQL_USER: orderuser
      MYSQL_PASSWORD: orderpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql

  order-service:
    build:
      context: ./Order
    container_name: order-service
    depends_on:
      - mysql
      - spring-crud-mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orderdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: orderuser
      SPRING_DATASOURCE_PASSWORD: orderpassword
    ports:
      - "8082:8082"
    volumes:
      - ./Order/target/Order-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]

volumes:
  mongo_data:
  mysql_order_data:
